services:
  postgres:
    image: postgres:17
    container_name: rielhome-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: rielhome
      POSTGRES_USER: rielhome
      POSTGRES_PASSWORD: rielhome
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:
    driver: local
