spring:
  application:
    name: evolforge
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${DB_USER:evolforge}
    password: ${DB_PASS:evolforge}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        format_sql: true
  flyway:
    enabled: true
    locations:
      - classpath:db/migration
  jackson:
    time-zone: UTC
  security:
    oauth2:
      client:
        registration: {}
        provider: {}
app:
  base-url: ${APP_BASE_URL:http://localhost:8080}
  auth:
    jwt:
      secret: ${JWT_SECRET:change-me-change-me-change-me-change-me-change-me-change-me-change}
      access-token-ttl: ${ACCESS_TOKEN_TTL:PT15M}
      issuer: ${JWT_ISSUER:rielhome}
    refresh-token:
      ttl: ${REFRESH_TOKEN_TTL:P30D}
    verification:
      ttl: ${VERIFICATION_TOKEN_TTL:PT24H}
    password-reset:
      ttl: ${PASSWORD_RESET_TTL:PT1H}
    password:
      encoder: ${PASSWORD_ENCODER:argon2}
  email:
    from: ${EMAIL_FROM:no-reply@rielhome.local}
    verification-base-url: ${EMAIL_VERIFICATION_BASE_URL:${app.base-url}/api/auth/verify-email}
    reset-base-url: ${EMAIL_RESET_BASE_URL:${app.base-url}/reset-password}
  oauth:
    google:
      client-id: ${GOOGLE_CLIENT_ID:}
      client-secret: ${GOOGLE_CLIENT_SECRET:}
      redirect-uri: ${GOOGLE_REDIRECT_URI:${app.base-url}/api/auth/google/callback}
server:
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
